
default: &default
  adapter: postgresql
  encoding: unicode
  username: take_a_hike
  password: hike

  pool: 5

development:
  <<: *default
  database: take_a_hike_development

test:
  <<: *default
  database: take_a_hike_test

url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: take_a_hike_production
  username: take_a_hike
  password: <%= ENV['TAKE_A_HIKE_DATABASE_PASSWORD'] %>
